### ISSUE TITLE
Crash when invalid signature is found

### ISSUE THREAD

**Issue by naydef** [nosoop/SMExt-SourceScramble#17]
Hello. Since the December 1, 2022 update Source Scramble seems to be crashing on encountering signature which is not found.

https://crash.limetech.org/bkuif7czlz43

Gamedata content:
```
"Games"
{
	"tf"
	{
		"Signatures"
		{
			"CTFPlayer::IsAllowedToTaunt"
			{
				"library" "server"
				"windows" "\x55\x8b\xec\x51\x56\x8b\xf1\x8b\x06\x8b\x80\x04\x01\x00\x00\xff\xd0\x84\xc0\x75"
			}
		}
		"MemPatches"
		{
			"CTFPlayer::IsAllowedToTaunt::IsStealthed()"
			{
				"signature" "CTFPlayer::IsAllowedToTaunt"
				"windows"
				{
					"offset"	"1DAh"
					"verify"	"\xE8\xE1\x04\x00\x00"
					"patch"		"\x31\xC0\x90\x90\x90"
				}
			}
		}
	}
}
```

**Comment by nosoop** [comment]
That should no longer be the case on 0.7.1; have you updated?
I'll recheck shortly myself.

**Comment by naydef** [comment]
Yea, i noticed right now we're using 0.7.0. Updating and will report

**Comment by naydef** [comment]
Yea, no more crashes due to outdated signature. I made this issue report prematurely before I tried to update.

Thanks for the help. Closing.
