### ISSUE TITLE
Patch keyvalue ignore wildcards 

### ISSUE THREAD

**Issue by LuxLuma** [nosoop/SMExt-SourceScramble#5]
Hey I would like to request "patch" keyvalue wildcards to ignore bytes.

Here is quick example

`"verify"		"\xF3\x0F\x10\x1D\x2A\x2A\x2A\x2A"`

`"patch"            "\x2A\x2A\x2A\x2A\x90\x90\x90\x90"`

First 4 bytes ignored in patching "F3 0F 10 1D" in this case. This would be easier to keep track in IDA since we can always start at beginning opcode.

**Comment by nosoop** [comment]
This is one of the things I wanted to solve with #3 (last paragraph in that issue).

It's possible to have a payload containing `\x2A` verbatim (e.g. inserting a `jmp` of length 42), which is why it currently doesn't behave that way.

**Comment by LuxLuma** [comment]
Ahh sorry about that making double post I saw it but did not understand it fully.

You know I totally forgot about that being used for other stuff, so use to SM, I read issue #3 
I understand better why `\x??` or `??` would be better.

Thanks for explanation keep up the good work 👍
