### ISSUE TITLE
Ability to allocate executable region of memory

### ISSUE THREAD

**Issue by dragokas** [nosoop/SMExt-SourceScramble#7]
Hi,
Can I ask you please to add a native for allocating memory with an executable flag?

I'd like to solve some crash by inserting 
```
if (x != NULL)
```
in arbitrary place inside the function, so using your extension, I could do a manual detour by jumping to a new executable memory, do a required check, and jump back.

Thanks in advance.
Nice job on this very useful extension!

**Comment by nosoop** [comment]
Provided you're using `StoreToAddress` or `MemoryBlock.StoreToOffset` (which just wraps around the former) to write to the `MemoryBlock`, [it should already be marking the region as executable](https://github.com/alliedmodders/sourcemod/blob/2653a450fc278f3479417aa193c4d36c77f133e0/core/logic/smn_core.cpp#L750-L766).

One of my private projects has no problems running executable code in `MemoryBlock`-allocated space, so I'm not sure that a new native is necessary for this.  But if it is, I have no issue with adding it (probably as a permissions property).

I'll leave this issue open for now; please try the extension then report back.

**Comment by dragokas** [comment]
Ahh, I'm sorry, I couldn't imagine that StoreToAddress() already cover that.
I just studying stuff so far, and didn't try to exec anything yet.
If you said, you already did it before, that's great and no additional natives required.
Thanks for clarifying.
